import {useEffect,useMemo,useState} from"react";import{Users,UserPlus,Search,X,Trash2,Fingerprint,MapPin}from"lucide-react";
const B="http://127.0.0.1:8000",A=`${B}/api`;
async function csrf(){let r=await fetch(`${B}/sanctum/csrf-cookie`,{credentials:"include",headers:{Accept:"application/json"}});if(!r.ok)throw Error("تعذر تهيئة الاتصال الآمن.");}
function token(){let c=document.cookie.split("; ").find(x=>x.startsWith("XSRF-TOKEN="));return c?decodeURIComponent(c.substring(11)):""}
async function api(u,o={}){let m=String(o.method||"GET").toUpperCase(),w=!["GET","HEAD","OPTIONS"].includes(m);if(w)await csrf();return fetch(u,{...o,credentials:"include",headers:{Accept:"application/json",...(w?{"Content-Type":"application/json"}:{}),...(w&&token()?{"X-XSRF-TOKEN":token()}:{}),...(o.headers||{})}})}
async function res(r){let x={};try{x=await r.json()}catch{}if(!r.ok||x.success===false)throw Error(Object.values(x.errors||{}).flat()[0]||x.message||"تعذر تنفيذ العملية.");return x}
const name=e=>e?.full_name||[e?.first_name,e?.middle_name,e?.last_name].filter(Boolean).join(" ")||"—";
export default function ProjectTeamPanel({projectId,project}){const[members,setMembers]=useState([]),[employees,setEmployees]=useState([]),[open,setOpen]=useState(false),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[msg,setMsg]=useState(""),[form,setForm]=useState({employee_id:"",role:"",start_date:"",end_date:"",attendance_enabled:true,notes:""});
const load=async()=>{if(!projectId)return;try{setError("");let x=await res(await api(`${A}/projects/${projectId}/team`));setMembers(x.data||[])}catch(e){setError(e.message)}};useEffect(()=>{load()},[projectId]);
const show=async()=>{setOpen(true);try{let x=await res(await api(`${A}/project-team/employees`));setEmployees(x.data||[])}catch(e){setError(e.message)}};
const available=useMemo(()=>{let ids=new Set(members.map(m=>m.employee_id)),q=search.toLowerCase();return employees.filter(e=>!ids.has(e.id)&&(!q||`${e.employee_number} ${name(e)} ${e.department?.name||""}`.toLowerCase().includes(q)))},[employees,members,search]);
const add=async()=>{if(!form.employee_id)return setError("اختر الموظف.");try{setBusy(true);let x=await res(await api(`${A}/projects/${projectId}/team`,{method:"POST",body:JSON.stringify({...form,employee_id:+form.employee_id,start_date:form.start_date||null,end_date:form.end_date||null})}));setMsg(x.message);setOpen(false);setForm({employee_id:"",role:"",start_date:"",end_date:"",attendance_enabled:true,notes:""});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
const del=async m=>{if(!confirm(`إزالة ${name(m.employee)} من فريق المشروع؟`))return;try{await res(await api(`${A}/projects/${projectId}/team/${m.id}`,{method:"DELETE"}));await load()}catch(e){setError(e.message)}};
return <section id="project-team-section" className="pt"><style>{`.pt{background:#fff;border:1px solid #ececf4;border-radius:18px;padding:20px}.pth,.pttitle,.person{display:flex;align-items:center}.pth{justify-content:space-between;gap:12px}.pttitle{gap:9px}.pttitle h3{margin:0}.primary{border:0;background:#6657F5;color:#fff;border-radius:10px;padding:10px 14px;font-weight:800;display:flex;gap:6px;align-items:center;cursor:pointer}.site{margin:14px 0;padding:11px;background:#fafafe;border:1px solid #eee;border-radius:11px;display:flex;gap:8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:10px}.card{border:1px solid #e8e9ef;border-radius:13px;padding:14px}.person{gap:10px}.avatar{width:40px;height:40px;background:#f0eeff;color:#6657F5;border-radius:11px;display:grid;place-items:center;font-weight:900}.meta{font-size:12px;color:#7b8498}.tags{display:flex;gap:6px;margin-top:10px}.tag{font-size:12px;background:#f5f6fa;border-radius:99px;padding:5px 8px}.ok{background:#ecfdf5;color:#047857}.foot{display:flex;justify-content:space-between;margin-top:10px}.del{border:0;background:#fff1f2;color:#be123c;border-radius:8px;width:32px;height:32px}.empty{padding:22px;text-align:center;color:#8b93a7;border:1px dashed #ddd;border-radius:12px}.modal{position:fixed;inset:0;background:#11182777;z-index:10000;display:grid;place-items:center}.dialog{width:min(700px,94vw);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:20px}.dh{display:flex;justify-content:space-between}.search input,.field input,.field textarea{width:100%;box-sizing:border-box;padding:10px;border:1px solid #ddd;border-radius:9px}.emps{max-height:220px;overflow:auto;margin:10px 0;border:1px solid #eee}.emp{padding:10px;border-bottom:1px solid #eee;cursor:pointer}.sel{background:#f3f1ff}.form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field.full{grid-column:1/-1}.field label{display:block;font-size:12px;font-weight:800;margin-bottom:4px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.err{background:#fff1f2;color:#be123c;padding:9px;margin:10px 0}.good{background:#ecfdf5;color:#047857;padding:9px;margin:10px 0}`}</style>
<div className="pth"><div className="pttitle"><Users/><div><h3>فريق المشروع والحضور</h3><div className="meta">{members.length} موظف</div></div></div><button className="primary" onClick={show}><UserPlus size={16}/>إضافة موظف</button></div><div className="site"><MapPin size={18}/><div><b>{project?.site_name||"موقع المشروع"}</b><div className="meta">{project?.site_address||project?.site_city||"العنوان غير محدد"} · نطاق الحضور {project?.attendance_radius||100} متر</div></div></div>{error&&<div className="err">{error}</div>}{msg&&<div className="good">{msg}</div>}
{members.length?<div className="grid">{members.map(m=><div className="card" key={m.id}><div className="person"><div className="avatar">{m.employee?.first_name?.[0]||"?"}</div><div><b>{name(m.employee)}</b><div className="meta">{m.employee?.employee_number} · {m.employee?.job_title?.name||"—"}</div></div></div><div className="tags"><span className="tag">{m.role||"عضو فريق"}</span><span className={`tag ${m.attendance_enabled?"ok":""}`}><Fingerprint size={11}/> {m.attendance_enabled?"الحضور مفعل":"غير مفعل"}</span></div><div className="foot"><span className="meta">{m.start_date?`من ${m.start_date}`:"بدون تاريخ"}</span><button className="del" onClick={()=>del(m)}><Trash2 size={14}/></button></div></div>)}</div>:<div className="empty">لم تتم إضافة موظفين للمشروع بعد.</div>}
{open&&<div className="modal"><div className="dialog"><div className="dh"><h3>إضافة موظف للمشروع</h3><button onClick={()=>setOpen(false)}><X/></button></div><div className="search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالاسم أو الرقم الوظيفي..."/></div><div className="emps">{available.map(e=><div key={e.id} className={`emp ${+form.employee_id===e.id?"sel":""}`} onClick={()=>setForm(f=>({...f,employee_id:e.id}))}><b>{name(e)}</b><div className="meta">{e.employee_number} · {e.department?.name||"—"} · {e.job_title?.name||"—"}</div></div>)}</div><div className="form"><div className="field full"><label>الدور في المشروع</label><input value={form.role} onChange={e=>setForm(f=>({...f,role:e.target.value}))}/></div><div className="field"><label>البداية</label><input type="date" value={form.start_date} onChange={e=>setForm(f=>({...f,start_date:e.target.value}))}/></div><div className="field"><label>النهاية</label><input type="date" value={form.end_date} onChange={e=>setForm(f=>({...f,end_date:e.target.value}))}/></div><div className="field full"><label><input type="checkbox" checked={form.attendance_enabled} onChange={e=>setForm(f=>({...f,attendance_enabled:e.target.checked}))}/> السماح بتسجيل الحضور من موقع المشروع</label></div><div className="field full"><label>ملاحظات</label><textarea value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></div></div><div className="actions"><button onClick={()=>setOpen(false)}>إلغاء</button><button className="primary" disabled={busy} onClick={add}>{busy?"جاري الإضافة...":"إضافة للفريق"}</button></div></div></div>}</section>}
