import {ArrowUpRight,ArrowDownRight,Search,SlidersHorizontal,Sparkles,ChevronRight} from "lucide-react";
export function SalesPage({title,subtitle,eyebrow="MASA SALES",actions,children}){return <section className="ms-page"><div className="ms-page-head"><div><span className="ms-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div><div className="ms-head-actions">{actions}</div></div>{children}</section>}
export function PrimaryButton({children,onClick}){return <button className="ms-btn ms-btn-primary" onClick={onClick}>{children}</button>}
export function GhostButton({children,onClick}){return <button className="ms-btn" onClick={onClick}>{children}</button>}
export function FilterBar({children}){return <div className="ms-filterbar">{children}</div>}
export function FilterButton({children}){return <button className="ms-filter"><SlidersHorizontal size={14}/>{children}</button>}
export function SearchBox({placeholder="Search..."}){return <div className="ms-search"><Search size={15}/><input placeholder={placeholder}/></div>}
export function KpiGrid({items}){return <div className="ms-kpi-grid">{items.map(x=><article className={"ms-kpi tone-"+(x.tone||"purple")} key={x.label}><div className="ms-kpi-label">{x.label}</div><div className="ms-kpi-value">{x.value}</div><div className={"ms-kpi-delta "+(String(x.delta).startsWith("-")?"down":"")}>{String(x.delta).startsWith("-")?<ArrowDownRight size={13}/>:<ArrowUpRight size={13}/>} {x.delta}</div></article>)}</div>}
export function Card({title,subtitle,children,className=""}){return <article className={"ms-card "+className}>{title&&<div className="ms-card-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>}{children}</article>}
export function Status({children}){const s=String(children||"").toLowerCase();const t=s.includes("healthy")||s.includes("paid")||s.includes("active")?"success":s.includes("risk")||s.includes("critical")||s.includes("overdue")?"danger":s.includes("watch")||s.includes("partial")||s.includes("renewal")?"warning":"info";return <span className={"ms-status "+t}>{children}</span>}
export function Score({value}){return <span className={"ms-score "+(value>=80?"hot":value>=60?"warm":"cold")}>{value}</span>}
export function DataTable({columns,rows,onRowClick}){return <div className="ms-table-wrap"><table className="ms-table"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i} onClick={()=>onRowClick?.(r)}>{columns.map(c=><td key={c.key}>{c.render?c.render(r[c.key],r):r[c.key]}</td>)}</tr>)}</tbody></table></div>}
export function MiniBars({values=[35,44,52,48,63,71,68,82,88,94]}){const m=Math.max(...values);return <div className="ms-mini-bars">{values.map((v,i)=><i key={i} style={{height:`${Math.max(14,v/m*100)}%`}}/>)}</div>}
export function InsightPanel(){return <Card className="ms-insight-card"><div className="ms-insight-title"><span><Sparkles size={16}/> MASA Sales Intelligence</span><button>Open Intelligence <ChevronRight size={14}/></button></div><div className="ms-insight-grid"><div><b>5</b><span>deals need attention</span></div><div><b>SAR 420K</b><span>pipeline at risk</span></div><div><b>3</b><span>probability increases</span></div><div><b>6</b><span>renewal opportunities</span></div></div></Card>}
