<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\BankReconciliation;
use App\Models\BankStatementLine;
use App\Models\FinanceAccount;
use App\Models\FinanceJournalLine;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class BankReconciliationController extends Controller {
 public function accounts(){return response()->json(['success'=>true,'data'=>FinanceAccount::where('is_cash_account',true)->where('is_active',true)->where('is_postable',true)->orderBy('code')->get(['id','code','name','name_en','normal_balance'])]);}
 public function index(Request $r){$q=BankReconciliation::with('account:id,code,name,name_en')->withCount(['lines','lines as matched_lines_count'=>fn($x)=>$x->where('match_status','matched')])->latest('id');if($r->filled('finance_account_id'))$q->where('finance_account_id',$r->integer('finance_account_id'));return response()->json(['success'=>true,'data'=>$q->get()]);}
 public function store(Request $r){$d=$r->validate(['finance_account_id'=>'required|exists:finance_accounts,id','period_from'=>'required|date','period_to'=>'required|date|after_or_equal:period_from','statement_opening_balance'=>'required|numeric','statement_closing_balance'=>'required|numeric','notes'=>'nullable|string|max:2000']);$a=FinanceAccount::whereKey($d['finance_account_id'])->where('is_cash_account',true)->where('is_active',true)->where('is_postable',true)->first();if(!$a)throw ValidationException::withMessages(['finance_account_id'=>['الحساب ليس حساب بنك/نقدية صالحًا للتسوية.']]);$s=$this->systemBalance($a->id,$d['period_to']);$rec=BankReconciliation::create([...$d,'system_closing_balance'=>$s,'difference'=>round((float)$d['statement_closing_balance']-$s,2),'created_by'=>$r->user()?->id]);return response()->json(['success'=>true,'message'=>'تم إنشاء التسوية البنكية.','data'=>$rec->load('account')],201);}
 public function show(BankReconciliation $bankReconciliation){$s=$this->systemBalance($bankReconciliation->finance_account_id,$bankReconciliation->period_to);$bankReconciliation->update(['system_closing_balance'=>$s,'difference'=>round((float)$bankReconciliation->statement_closing_balance-$s,2)]);$used=BankStatementLine::where('bank_reconciliation_id',$bankReconciliation->id)->whereNotNull('finance_journal_line_id')->pluck('finance_journal_line_id');$system=FinanceJournalLine::with('journalEntry:id,entry_number,entry_date,description,reference_number,status')->where('account_id',$bankReconciliation->finance_account_id)->whereHas('journalEntry',fn($q)=>$q->where('status','posted')->whereBetween('entry_date',[$bankReconciliation->period_from,$bankReconciliation->period_to]))->whereNotIn('id',$used)->get()->map(fn($l)=>['id'=>$l->id,'date'=>$l->journalEntry->entry_date,'entry_number'=>$l->journalEntry->entry_number,'reference_number'=>$l->journalEntry->reference_number,'description'=>$l->description?:$l->journalEntry->description,'amount'=>round((float)$l->debit-(float)$l->credit,2)]);return response()->json(['success'=>true,'data'=>['reconciliation'=>$bankReconciliation->load(['account','lines.journalLine.journalEntry']),'system_lines'=>$system]]);}
 public function import(Request $r,BankReconciliation $bankReconciliation){if($bankReconciliation->status==='completed')throw ValidationException::withMessages(['file'=>['التسوية مكتملة ولا يمكن تعديلها.']]);$r->validate(['file'=>'required|file|mimes:csv,txt|max:5120']);$h=fopen($r->file('file')->getRealPath(),'r');$header=fgetcsv($h);$count=0;DB::transaction(function()use($h,$header,$bankReconciliation,&$count){while(($row=fgetcsv($h))!==false){if(count($row)!==count($header))continue;$x=array_combine(array_map(fn($v)=>strtolower(trim($v)),$header),$row);$date=$x['date']??$x['transaction_date']??null;if(!$date)continue;$debit=(float)($x['debit']??0);$credit=(float)($x['credit']??0);$amount=isset($x['amount'])?(float)$x['amount']:$debit-$credit;BankStatementLine::create(['bank_reconciliation_id'=>$bankReconciliation->id,'transaction_date'=>$date,'description'=>$x['description']??null,'reference_number'=>$x['reference']??$x['reference_number']??null,'debit'=>$debit,'credit'=>$credit,'amount'=>round($amount,2)]);$count++;}});fclose($h);return response()->json(['success'=>true,'message'=>"تم استيراد {$count} حركة.",'data'=>['imported'=>$count]]);}
 public function autoMatch(Request $r,BankReconciliation $bankReconciliation){$matched=0;DB::transaction(function()use($r,$bankReconciliation,&$matched){foreach($bankReconciliation->lines()->where('match_status','unmatched')->get() as $line){$candidate=FinanceJournalLine::where('account_id',$bankReconciliation->finance_account_id)->whereHas('journalEntry',fn($q)=>$q->where('status','posted')->whereBetween('entry_date',[$line->transaction_date->copy()->subDays(3),$line->transaction_date->copy()->addDays(3)]))->whereDoesntHave('bankStatementLines')->get()->first(fn($j)=>abs(((float)$j->debit-(float)$j->credit)-(float)$line->amount)<.01);if($candidate){$line->update(['match_status'=>'matched','finance_journal_line_id'=>$candidate->id,'matched_by'=>$r->user()?->id,'matched_at'=>now()]);$matched++;}}});return response()->json(['success'=>true,'message'=>"تمت مطابقة {$matched} حركة تلقائيًا."]);}
 public function match(Request $r,BankReconciliation $bankReconciliation,BankStatementLine $line){$d=$r->validate(['finance_journal_line_id'=>'required|exists:finance_journal_lines,id']);abort_unless($line->bank_reconciliation_id===$bankReconciliation->id,404);$line->update(['match_status'=>'matched','finance_journal_line_id'=>$d['finance_journal_line_id'],'matched_by'=>$r->user()?->id,'matched_at'=>now()]);return response()->json(['success'=>true,'message'=>'تمت المطابقة.']);}
 public function unmatch(BankReconciliation $bankReconciliation,BankStatementLine $line){abort_unless($line->bank_reconciliation_id===$bankReconciliation->id,404);$line->update(['match_status'=>'unmatched','finance_journal_line_id'=>null,'matched_by'=>null,'matched_at'=>null]);return response()->json(['success'=>true,'message'=>'تم إلغاء المطابقة.']);}
 public function complete(Request $r,BankReconciliation $bankReconciliation){$n=$bankReconciliation->lines()->where('match_status','unmatched')->count();if($n)throw ValidationException::withMessages(['status'=>["يوجد {$n} حركة غير مطابقة."]]);$s=$this->systemBalance($bankReconciliation->finance_account_id,$bankReconciliation->period_to);$d=round((float)$bankReconciliation->statement_closing_balance-$s,2);if(abs($d)>=.01)throw ValidationException::withMessages(['difference'=>['لا يمكن الإقفال قبل أن يصبح الفرق صفرًا.']]);$bankReconciliation->update(['status'=>'completed','system_closing_balance'=>$s,'difference'=>$d,'completed_by'=>$r->user()?->id,'completed_at'=>now()]);return response()->json(['success'=>true,'message'=>'تم إقفال التسوية البنكية بنجاح.']);}
 private function systemBalance(int $id,$to):float{return round((float)FinanceJournalLine::where('account_id',$id)->whereHas('journalEntry',fn($q)=>$q->where('status','posted')->whereDate('entry_date','<=',$to))->selectRaw('COALESCE(SUM(debit-credit),0) balance')->value('balance'),2);}
}
