<?php
namespace App\Http\Controllers\Api\HrV2;
use App\Http\Controllers\Controller;use App\Models\HrAttendanceCorrectionRequest;use App\Models\HrAttendanceDaily;use App\Models\HrAttendanceDailySummary;use App\Models\HrAttendanceEvent;use App\Models\HrEmployee;use App\Models\HrLeaveRequest;use App\Models\HrOvertimeRequest;use App\Services\Hr\AttendanceProcessor;use Carbon\CarbonPeriod;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class AttendanceRequestController extends Controller{
 public function corrections(Request $r){return response()->json(HrAttendanceCorrectionRequest::with('employee')->latest()->paginate($r->integer('per_page',50)));}
 public function overtime(Request $r){return response()->json(HrOvertimeRequest::with('employee')->latest()->paginate($r->integer('per_page',50)));}
 public function leaves(Request $r){return response()->json(HrLeaveRequest::with('employee')->latest()->paginate($r->integer('per_page',50)));}
 public function reviewCorrection(Request $r,HrAttendanceCorrectionRequest $request,AttendanceProcessor $processor){$d=$r->validate(['action'=>'required|in:approve,reject','notes'=>'nullable|string']);abort_unless($request->status==='pending',422,'تمت مراجعة الطلب مسبقاً.');DB::transaction(function()use($request,$d,$r,$processor){$request->update(['status'=>$d['action']==='approve'?'approved':'rejected','reviewed_by'=>$r->user()?->id,'review_notes'=>$d['notes']??null,'reviewed_at'=>now()]);if($d['action']==='approve'){$day=$request->work_date->toDateString();HrAttendanceEvent::where('employee_id',$request->employee_id)->where('source','manual')->whereDate('event_at',$day)->where('meta->correction_request_id',$request->id)->delete();if($request->requested_check_in)HrAttendanceEvent::create(['employee_id'=>$request->employee_id,'event_type'=>'check_in','event_at'=>$request->requested_check_in,'source'=>'manual','meta'=>['correction_request_id'=>$request->id]]);if($request->requested_check_out)HrAttendanceEvent::create(['employee_id'=>$request->employee_id,'event_type'=>'check_out','event_at'=>$request->requested_check_out,'source'=>'manual','meta'=>['correction_request_id'=>$request->id]]);$processor->rebuildDay(HrEmployee::findOrFail($request->employee_id),$day,$r->user()?->id);}});return response()->json(['success'=>true,'data'=>$request->fresh('employee')]);}
 public function reviewOvertime(Request $r,HrOvertimeRequest $request){$d=$r->validate(['action'=>'required|in:approve,reject','approved_minutes'=>'nullable|integer|min:0']);abort_unless($request->status==='pending',422,'تمت مراجعة الطلب مسبقاً.');DB::transaction(function()use($request,$d,$r){$minutes=$d['action']==='approve'?($d['approved_minutes']??$request->requested_minutes):0;$request->update(['status'=>$d['action']==='approve'?'approved':'rejected','approved_minutes'=>$minutes,'approved_by'=>$r->user()?->id,'approved_at'=>now()]);if($d['action']==='approve'){HrAttendanceDaily::where('employee_id',$request->employee_id)->whereDate('attendance_date',$request->work_date)->update(['overtime_minutes'=>$minutes]);HrAttendanceDailySummary::where('employee_id',$request->employee_id)->whereDate('work_date',$request->work_date)->update(['overtime_minutes'=>$minutes]);}});return response()->json(['success'=>true,'data'=>$request->fresh('employee')]);}
 public function reviewLeave(Request $r,HrLeaveRequest $request){$d=$r->validate(['action'=>'required|in:approve,reject']);abort_unless(in_array($request->status,['draft','pending'],true),422,'تمت مراجعة الطلب مسبقاً.');DB::transaction(function()use($request,$d,$r){$request->update(['status'=>$d['action']==='approve'?'approved':'rejected','approved_by'=>$r->user()?->id,'approved_at'=>now()]);if($d['action']==='approve')foreach(CarbonPeriod::create($request->start_date,$request->end_date) as $date){$day=$date->toDateString();HrAttendanceDaily::updateOrCreate(['employee_id'=>$request->employee_id,'attendance_date'=>$day],['status'=>'on_leave','source'=>'system','calculated_at'=>now(),'updated_by'=>$r->user()?->id]);HrAttendanceDailySummary::updateOrCreate(['employee_id'=>$request->employee_id,'work_date'=>$day],['status'=>'leave']);}});return response()->json(['success'=>true,'data'=>$request->fresh('employee')]);}
}