<?php
namespace App\Http\Controllers\Api\HrV2;
use App\Http\Controllers\Controller;use App\Models\HrAttendanceCorrectionRequest;use App\Models\HrAttendanceEvent;use App\Models\HrEmployee;use App\Models\HrLeaveRequest;use App\Models\HrOvertimeRequest;use App\Services\Hr\AttendanceProcessor;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class AttendanceRequestController{
 public function corrections(Request $r){return response()->json(HrAttendanceCorrectionRequest::with('employee')->latest()->paginate($r->integer('per_page',50)));}
 public function overtime(Request $r){return response()->json(HrOvertimeRequest::with('employee')->latest()->paginate($r->integer('per_page',50)));}
 public function leaves(Request $r){return response()->json(HrLeaveRequest::with('employee')->latest()->paginate($r->integer('per_page',50)));}
 public function reviewCorrection(Request $r,HrAttendanceCorrectionRequest $request,AttendanceProcessor $processor){$d=$r->validate(['action'=>'required|in:approve,reject','notes'=>'nullable|string']);abort_unless($request->status==='pending',422,'تمت مراجعة الطلب مسبقاً.');DB::transaction(function()use($request,$d,$r,$processor){$request->update(['status'=>$d['action']==='approve'?'approved':'rejected','reviewed_by'=>$r->user()?->id,'review_notes'=>$d['notes']??null,'reviewed_at'=>now()]);if($d['action']==='approve'){if($request->requested_check_in)HrAttendanceEvent::create(['employee_id'=>$request->employee_id,'event_type'=>'check_in','event_at'=>$request->requested_check_in,'source'=>'manual','meta'=>['correction_request_id'=>$request->id]]);if($request->requested_check_out)HrAttendanceEvent::create(['employee_id'=>$request->employee_id,'event_type'=>'check_out','event_at'=>$request->requested_check_out,'source'=>'manual','meta'=>['correction_request_id'=>$request->id]]);$processor->rebuildDay(HrEmployee::findOrFail($request->employee_id),$request->work_date->toDateString(),$r->user()?->id);}});return response()->json(['success'=>true,'data'=>$request->fresh('employee')]);}
 public function reviewOvertime(Request $r,HrOvertimeRequest $request){$d=$r->validate(['action'=>'required|in:approve,reject','approved_minutes'=>'nullable|integer|min:0']);abort_unless($request->status==='pending',422,'تمت مراجعة الطلب مسبقاً.');$request->update(['status'=>$d['action']==='approve'?'approved':'rejected','approved_minutes'=>$d['action']==='approve'?($d['approved_minutes']??$request->requested_minutes):0,'approved_by'=>$r->user()?->id,'approved_at'=>now()]);return response()->json(['success'=>true,'data'=>$request->fresh('employee')]);}
 public function reviewLeave(Request $r,HrLeaveRequest $request){$d=$r->validate(['action'=>'required|in:approve,reject']);abort_unless(in_array($request->status,['draft','pending'],true),422,'تمت مراجعة الطلب مسبقاً.');$request->update(['status'=>$d['action']==='approve'?'approved':'rejected','approved_by'=>$r->user()?->id,'approved_at'=>now()]);return response()->json(['success'=>true,'data'=>$request->fresh('employee')]);}
}