<?php
namespace App\Http\Controllers\Api\HrV2;
use App\Http\Controllers\Controller;use App\Models\HrRequisition;use App\Models\HrCandidate;use App\Models\HrApplication;use Illuminate\Http\Request;
class RecruitmentController extends Controller{
 public function dashboard(){return response()->json(['open_requisitions'=>HrRequisition::where('status','open')->count(),'active_candidates'=>HrCandidate::whereIn('status',['new','active'])->count(),'active_applications'=>HrApplication::where('status','active')->count(),'offers'=>HrApplication::where('status','offer')->count(),'requisitions'=>HrRequisition::withCount('applications')->latest()->limit(50)->get(),'pipeline'=>HrApplication::selectRaw('stage,count(*) total')->where('status','active')->groupBy('stage')->get()]);}
 public function candidates(Request $r){$q=HrCandidate::query();if($r->search)$q->where(fn($x)=>$x->where('first_name','like',"%{$r->search}%")->orWhere('last_name','like',"%{$r->search}%")->orWhere('email','like',"%{$r->search}%"));return response()->json($q->latest()->paginate($r->integer('per_page',50)));}
 public function storeRequisition(Request $r){$d=$r->validate(['title'=>'required|string|max:255','department_id'=>'nullable|exists:hr_departments,id','position_id'=>'nullable|exists:hr_positions,id','hiring_manager_id'=>'nullable|exists:hr_employees,id','headcount'=>'required|integer|min:1','budget_min'=>'nullable|numeric|min:0','budget_max'=>'nullable|numeric|min:0','employment_type'=>'required|in:full_time,part_time,contract,temporary,intern','description'=>'nullable|string','target_date'=>'nullable|date']);$d['requisition_number']='REQ-'.now()->format('YmdHis');$d['created_by']=$r->user()?->id;return response()->json(HrRequisition::create($d),201);}
 public function storeCandidate(Request $r){$d=$r->validate(['first_name'=>'required|string','last_name'=>'nullable|string','email'=>'nullable|email','mobile'=>'nullable|string','nationality'=>'nullable|string','city'=>'nullable|string','current_title'=>'nullable|string','years_experience'=>'nullable|numeric|min:0','source'=>'nullable|string']);$d['candidate_number']='CAN-'.now()->format('YmdHis');return response()->json(HrCandidate::create($d),201);}
 public function storeApplication(Request $r){$d=$r->validate(['requisition_id'=>'required|exists:hr_requisitions,id','candidate_id'=>'required|exists:hr_candidates,id']);return response()->json(HrApplication::firstOrCreate($d,['stage'=>'applied','status'=>'active']),201);}
 public function moveApplication(Request $r,HrApplication $application){$d=$r->validate(['stage'=>'required|string|max:60','status'=>'nullable|in:active,offer,hired,rejected,withdrawn','notes'=>'nullable|string']);$application->update($d);return response()->json($application->fresh());}
}