import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, FileUp, Landmark, Loader2, RefreshCw, Sparkles } from "lucide-react";
import "./bank-reconciliation.css";
const API="http://127.0.0.1:8000/api";
const money=v=>new Intl.NumberFormat("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
const today=new Date().toISOString().slice(0,10);
const monthStart=`${today.slice(0,7)}-01`;
export default function BankReconciliation({onChangeView}){
 const [accounts,setAccounts]=useState([]),[list,setList]=useState([]),[detail,setDetail]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [form,setForm]=useState({finance_account_id:"",period_from:monthStart,period_to:today,statement_opening_balance:"0",statement_closing_balance:"0",notes:""});
 const request=async(path,options={})=>{const r=await fetch(`${API}${path}`,{headers:{Accept:"application/json",...(options.body instanceof FormData?{}:{"Content-Type":"application/json"})},...options});const j=await r.json();if(!r.ok)throw new Error(j?.message||Object.values(j?.errors||{}).flat()[0]||"تعذر تنفيذ العملية");return j;};
 const load=async()=>{setLoading(true);try{const [a,l]=await Promise.all([request("/finance/bank-reconciliation/accounts"),request("/finance/bank-reconciliations")]);setAccounts(a.data||[]);setList(l.data||[]);if(!form.finance_account_id&&a.data?.[0])setForm(x=>({...x,finance_account_id:String(a.data[0].id)}));}catch(e){setMessage(e.message)}finally{setLoading(false)}};
 const open=async id=>{setBusy(true);try{const j=await request(`/finance/bank-reconciliations/${id}`);setDetail(j.data)}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const act=async(path,options={})=>{setBusy(true);setMessage("");try{const j=await request(path,options);setMessage(j.message||"تمت العملية");if(detail)await open(detail.reconciliation.id);await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const create=e=>{e.preventDefault();act("/finance/bank-reconciliations",{method:"POST",body:JSON.stringify(form)})};
 const upload=e=>{const f=e.target.files?.[0];if(!f||!detail)return;const fd=new FormData();fd.append("file",f);act(`/finance/bank-reconciliations/${detail.reconciliation.id}/import`,{method:"POST",body:fd});e.target.value=""};
 const rec=detail?.reconciliation, lines=rec?.lines||[], matched=lines.filter(x=>x.match_status==="matched").length;
 const summary=useMemo(()=>({count:lines.length,matched,unmatched:lines.length-matched}),[lines,matched]);
 return <div className="br-page" dir="rtl">
  <header className="br-head"><div><button className="br-back" onClick={()=>onChangeView?.("finance-banks")}><ArrowRight size={18}/>البنوك والخزينة</button><h1>التسوية البنكية</h1><p>مطابقة كشف البنك مع القيود المرحلة دون تعديل بيانات القيود الأصلية.</p></div><button className="br-soft" onClick={load}><RefreshCw size={18}/>تحديث</button></header>
  {message&&<div className="br-message">{message}</div>}
  <section className="br-card"><h2>إنشاء فترة تسوية</h2><form className="br-form" onSubmit={create}><label>الحساب<select required value={form.finance_account_id} onChange={e=>setForm({...form,finance_account_id:e.target.value})}><option value="">اختر الحساب</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>من<input type="date" value={form.period_from} onChange={e=>setForm({...form,period_from:e.target.value})}/></label><label>إلى<input type="date" value={form.period_to} onChange={e=>setForm({...form,period_to:e.target.value})}/></label><label>رصيد أول الكشف<input type="number" step="0.01" value={form.statement_opening_balance} onChange={e=>setForm({...form,statement_opening_balance:e.target.value})}/></label><label>رصيد آخر الكشف<input type="number" step="0.01" value={form.statement_closing_balance} onChange={e=>setForm({...form,statement_closing_balance:e.target.value})}/></label><button className="br-primary" disabled={busy}>إنشاء التسوية</button></form></section>
  <section className="br-card"><h2>فترات التسوية</h2>{loading?<div className="br-state"><Loader2 className="br-spin"/>جاري التحميل</div>:<div className="br-table-wrap"><table><thead><tr><th>الحساب</th><th>الفترة</th><th>رصيد الكشف</th><th>رصيد النظام</th><th>الفرق</th><th>الحالة</th><th></th></tr></thead><tbody>{list.map(x=><tr key={x.id}><td>{x.account?.code} — {x.account?.name}</td><td>{x.period_from} — {x.period_to}</td><td>{money(x.statement_closing_balance)}</td><td>{money(x.system_closing_balance)}</td><td className={Math.abs(Number(x.difference))<.01?"br-ok":"br-bad"}>{money(x.difference)}</td><td><span className={`br-pill ${x.status}`}>{x.status==="completed"?"مقفلة":"مسودة"}</span></td><td><button className="br-link" onClick={()=>open(x.id)}>فتح</button></td></tr>)}</tbody></table></div>}</section>
  {rec&&<section className="br-card br-detail"><div className="br-detail-head"><div><h2>{rec.account?.code} — {rec.account?.name}</h2><p>{rec.period_from} إلى {rec.period_to}</p></div><div className="br-actions"><label className="br-soft"><FileUp size={18}/>استيراد CSV<input hidden type="file" accept=".csv,.txt" onChange={upload}/></label><button className="br-soft" disabled={busy||rec.status==="completed"} onClick={()=>act(`/finance/bank-reconciliations/${rec.id}/auto-match`,{method:"POST"})}><Sparkles size={18}/>مطابقة تلقائية</button><button className="br-primary" disabled={busy||rec.status==="completed"} onClick={()=>act(`/finance/bank-reconciliations/${rec.id}/complete`,{method:"POST"})}><CheckCircle2 size={18}/>إقفال التسوية</button></div></div>
   <div className="br-kpis"><div><span>حركات الكشف</span><strong>{summary.count}</strong></div><div><span>مطابقة</span><strong className="br-ok">{summary.matched}</strong></div><div><span>غير مطابقة</span><strong className="br-bad">{summary.unmatched}</strong></div><div><span>الفرق</span><strong>{money(rec.difference)} ر.س</strong></div></div>
   <div className="br-columns"><div><h3>كشف البنك</h3>{lines.length?lines.map(x=><article className="br-line" key={x.id}><div><b>{x.description||"حركة بنكية"}</b><small>{x.transaction_date} · {x.reference_number||"بدون مرجع"}</small></div><strong>{money(x.amount)}</strong><span className={`br-pill ${x.match_status}`}>{x.match_status==="matched"?"مطابقة":"غير مطابقة"}</span>{x.match_status==="matched"&&rec.status!=="completed"&&<button onClick={()=>act(`/finance/bank-reconciliations/${rec.id}/lines/${x.id}/match`,{method:"DELETE"})}>إلغاء</button>}</article>):<p className="br-muted">استورد كشفًا بصيغة CSV: date, description, reference, debit, credit أو amount.</p>}</div><div><h3>قيود النظام غير المطابقة</h3>{(detail.system_lines||[]).map(x=><article className="br-line" key={x.id}><div><b>{x.description}</b><small>{x.date} · {x.entry_number}</small></div><strong>{money(x.amount)}</strong><select defaultValue="" onChange={e=>{const lineId=e.target.value;if(lineId)act(`/finance/bank-reconciliations/${rec.id}/lines/${lineId}/match`,{method:"POST",body:JSON.stringify({finance_journal_line_id:x.id})})}}><option value="">مطابقة مع حركة...</option>{lines.filter(l=>l.match_status==="unmatched").map(l=><option key={l.id} value={l.id}>{l.transaction_date} — {money(l.amount)}</option>)}</select></article>)}</div></div>
  </section>}
 </div>;
}
