<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  if(!Schema::hasTable('hr_branches')) Schema::create('hr_branches',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name');$t->string('name_en')->nullable();$t->string('country',2)->default('SA');$t->string('city')->nullable();$t->string('address')->nullable();$t->string('phone',50)->nullable();$t->string('email')->nullable();$t->string('timezone')->default('Asia/Riyadh');$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->unsignedInteger('attendance_radius')->default(100);$t->boolean('is_head_office')->default(false);$t->boolean('is_active')->default(true);$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->softDeletes();});
  if(!Schema::hasTable('hr_departments')) Schema::create('hr_departments',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name');$t->string('name_en')->nullable();$t->foreignId('parent_id')->nullable()->constrained('hr_departments')->nullOnDelete();$t->foreignId('branch_id')->nullable()->constrained('hr_branches')->nullOnDelete();$t->unsignedInteger('level')->default(1);$t->string('cost_center_code',60)->nullable();$t->string('email')->nullable();$t->string('phone',50)->nullable();$t->boolean('is_active')->default(true);$t->text('description')->nullable();$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->softDeletes();});
  if(!Schema::hasTable('hr_job_titles')) Schema::create('hr_job_titles',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name');$t->string('name_en')->nullable();$t->foreignId('department_id')->nullable()->constrained('hr_departments')->nullOnDelete();$t->string('grade',50)->nullable();$t->unsignedInteger('min_experience_years')->default(0);$t->decimal('min_salary',14,2)->nullable();$t->decimal('max_salary',14,2)->nullable();$t->text('description')->nullable();$t->text('responsibilities')->nullable();$t->text('requirements')->nullable();$t->boolean('is_active')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->softDeletes();});
  if(!Schema::hasTable('hr_shifts')) Schema::create('hr_shifts',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name');$t->string('name_en')->nullable();$t->time('start_time');$t->time('end_time');$t->boolean('crosses_midnight')->default(false);$t->unsignedInteger('required_minutes')->default(480);$t->unsignedInteger('late_grace_minutes')->default(0);$t->unsignedInteger('early_leave_grace_minutes')->default(0);$t->unsignedInteger('break_minutes')->default(0);$t->boolean('is_flexible')->default(false);$t->boolean('overtime_allowed')->default(false);$t->unsignedInteger('overtime_after_minutes')->default(0);$t->json('working_days')->nullable();$t->boolean('is_active')->default(true);$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->softDeletes();});
  if(!Schema::hasTable('hr_employees')) Schema::create('hr_employees',function(Blueprint $t){$t->id();$t->string('employee_number',30)->unique();$t->foreignId('user_id')->nullable()->unique()->constrained('users')->nullOnDelete();$t->string('first_name',100);$t->string('middle_name',100)->nullable();$t->string('last_name',100);$t->string('name_en')->nullable();$t->string('national_id',30)->nullable()->unique();$t->string('passport_number',30)->nullable()->unique();$t->string('nationality',60)->nullable();$t->enum('gender',['male','female'])->nullable();$t->date('birth_date')->nullable();$t->string('marital_status',30)->nullable();$t->string('work_email')->nullable()->unique();$t->string('personal_email')->nullable();$t->string('mobile',30)->nullable();$t->string('emergency_phone',30)->nullable();$t->string('address')->nullable();$t->string('photo_path')->nullable();$t->foreignId('branch_id')->nullable()->constrained('hr_branches')->nullOnDelete();$t->foreignId('department_id')->nullable()->constrained('hr_departments')->nullOnDelete();$t->foreignId('job_title_id')->nullable()->constrained('hr_job_titles')->nullOnDelete();$t->foreignId('shift_id')->nullable()->constrained('hr_shifts')->nullOnDelete();$t->foreignId('manager_id')->nullable()->constrained('hr_employees')->nullOnDelete();$t->string('biometric_user_id',60)->nullable();$t->date('hire_date')->nullable();$t->date('probation_end_date')->nullable();$t->enum('employment_type',['full_time','part_time','contract','temporary','intern'])->default('full_time');$t->enum('status',['draft','active','on_leave','suspended','terminated'])->default('active');$t->date('termination_date')->nullable();$t->text('termination_reason')->nullable();$t->string('bank_name')->nullable();$t->string('iban',40)->nullable();$t->boolean('is_active')->default(true);$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->softDeletes();});
 }
 public function down(): void {Schema::dropIfExists('hr_employees');Schema::dropIfExists('hr_shifts');Schema::dropIfExists('hr_job_titles');Schema::dropIfExists('hr_departments');Schema::dropIfExists('hr_branches');}
};