<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('hr_legal_entities',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name');$t->string('name_en')->nullable();$t->string('commercial_registration',50)->nullable();$t->string('unified_number',50)->nullable();$t->string('tax_number',50)->nullable();$t->string('country',2)->default('SA');$t->boolean('is_active')->default(true);$t->json('settings')->nullable();$t->timestamps();$t->softDeletes();});
  Schema::create('hr_grades',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name');$t->string('name_en')->nullable();$t->unsignedInteger('level')->default(1);$t->decimal('min_salary',14,2)->nullable();$t->decimal('max_salary',14,2)->nullable();$t->json('benefits')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->softDeletes();});
  Schema::create('hr_positions',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name');$t->string('name_en')->nullable();$t->foreignId('department_id')->nullable()->constrained('hr_departments')->nullOnDelete();$t->foreignId('job_title_id')->nullable()->constrained('hr_job_titles')->nullOnDelete();$t->foreignId('grade_id')->nullable()->constrained('hr_grades')->nullOnDelete();$t->foreignId('reports_to_position_id')->nullable()->constrained('hr_positions')->nullOnDelete();$t->unsignedInteger('headcount_budget')->default(1);$t->boolean('is_managerial')->default(false);$t->boolean('is_active')->default(true);$t->text('description')->nullable();$t->timestamps();$t->softDeletes();});
  Schema::create('hr_government_connectors',function(Blueprint $t){$t->id();$t->string('code',40)->unique();$t->string('name');$t->enum('channel',['api','manual','file_exchange','pending_accreditation'])->default('manual');$t->enum('status',['connected','disconnected','degraded','maintenance','not_configured'])->default('not_configured');$t->timestamp('last_sync_at')->nullable();$t->timestamp('last_success_at')->nullable();$t->text('last_error')->nullable();$t->json('settings')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('hr_government_transactions',function(Blueprint $t){$t->id();$t->foreignId('connector_id')->constrained('hr_government_connectors')->cascadeOnDelete();$t->foreignId('employee_id')->nullable()->constrained('hr_employees')->nullOnDelete();$t->string('transaction_type',80);$t->string('external_reference',120)->nullable();$t->enum('status',['draft','pending','processing','completed','failed','cancelled'])->default('pending');$t->json('request_payload')->nullable();$t->json('response_payload')->nullable();$t->text('error_message')->nullable();$t->timestamp('submitted_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();});
  Schema::create('hr_compliance_rules',function(Blueprint $t){$t->id();$t->string('code',60)->unique();$t->string('name');$t->string('category',60);$t->enum('severity',['info','low','medium','high','critical'])->default('medium');$t->json('configuration')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('hr_compliance_exceptions',function(Blueprint $t){$t->id();$t->foreignId('rule_id')->nullable()->constrained('hr_compliance_rules')->nullOnDelete();$t->foreignId('employee_id')->nullable()->constrained('hr_employees')->nullOnDelete();$t->string('title');$t->text('description')->nullable();$t->enum('severity',['info','low','medium','high','critical'])->default('medium');$t->enum('status',['open','acknowledged','resolved','dismissed'])->default('open');$t->date('due_date')->nullable();$t->timestamp('resolved_at')->nullable();$t->json('meta')->nullable();$t->timestamps();});
  Schema::create('hr_employee_lifecycle_events',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained('hr_employees')->cascadeOnDelete();$t->string('event_type',60);$t->date('effective_date');$t->string('title');$t->text('notes')->nullable();$t->json('before_data')->nullable();$t->json('after_data')->nullable();$t->timestamps();});
  Schema::table('hr_branches',function(Blueprint $t){$t->foreignId('legal_entity_id')->nullable()->constrained('hr_legal_entities')->nullOnDelete();});
  Schema::table('hr_employees',function(Blueprint $t){$t->foreignId('position_id')->nullable()->constrained('hr_positions')->nullOnDelete();$t->foreignId('grade_id')->nullable()->constrained('hr_grades')->nullOnDelete();});
 }
 public function down(): void {
  Schema::table('hr_employees',function(Blueprint $t){$t->dropConstrainedForeignId('grade_id');$t->dropConstrainedForeignId('position_id');});
  Schema::table('hr_branches',function(Blueprint $t){$t->dropConstrainedForeignId('legal_entity_id');});
  Schema::dropIfExists('hr_employee_lifecycle_events');Schema::dropIfExists('hr_compliance_exceptions');Schema::dropIfExists('hr_compliance_rules');Schema::dropIfExists('hr_government_transactions');Schema::dropIfExists('hr_government_connectors');Schema::dropIfExists('hr_positions');Schema::dropIfExists('hr_grades');Schema::dropIfExists('hr_legal_entities');
 }
};