<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('hr_goal_cycles',function(Blueprint $t){$t->id();$t->string('name');$t->date('start_date');$t->date('end_date');$t->enum('status',['draft','active','review','closed'])->default('draft');$t->timestamps();});
  Schema::create('hr_goals',function(Blueprint $t){$t->id();$t->foreignId('cycle_id')->constrained('hr_goal_cycles')->cascadeOnDelete();$t->foreignId('employee_id')->nullable()->constrained('hr_employees')->cascadeOnDelete();$t->foreignId('department_id')->nullable()->constrained('hr_departments')->nullOnDelete();$t->foreignId('parent_id')->nullable()->constrained('hr_goals')->nullOnDelete();$t->string('title');$t->text('description')->nullable();$t->decimal('weight',5,2)->default(100);$t->decimal('target_value',14,2)->nullable();$t->decimal('current_value',14,2)->nullable();$t->string('unit',40)->nullable();$t->unsignedInteger('progress')->default(0);$t->enum('status',['draft','active','completed','cancelled'])->default('draft');$t->timestamps();});
  Schema::create('hr_review_cycles',function(Blueprint $t){$t->id();$t->string('name');$t->enum('review_type',['manager','self_manager','360','probation'])->default('manager');$t->date('start_date');$t->date('end_date');$t->enum('status',['draft','active','calibration','closed'])->default('draft');$t->json('settings')->nullable();$t->timestamps();});
  Schema::create('hr_performance_reviews',function(Blueprint $t){$t->id();$t->foreignId('cycle_id')->constrained('hr_review_cycles')->cascadeOnDelete();$t->foreignId('employee_id')->constrained('hr_employees')->cascadeOnDelete();$t->foreignId('reviewer_employee_id')->nullable()->constrained('hr_employees')->nullOnDelete();$t->enum('reviewer_type',['self','manager','peer','direct_report','other'])->default('manager');$t->decimal('score',5,2)->nullable();$t->enum('status',['pending','in_progress','submitted','calibrated','acknowledged'])->default('pending');$t->json('answers')->nullable();$t->text('summary')->nullable();$t->timestamps();});
  Schema::create('hr_skills',function(Blueprint $t){$t->id();$t->string('code',50)->unique();$t->string('name');$t->string('category',80)->nullable();$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('hr_employee_skills',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained('hr_employees')->cascadeOnDelete();$t->foreignId('skill_id')->constrained('hr_skills')->cascadeOnDelete();$t->unsignedTinyInteger('level')->default(1);$t->unsignedTinyInteger('target_level')->nullable();$t->date('validated_at')->nullable();$t->foreignId('validated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['employee_id','skill_id']);});
  Schema::create('hr_learning_courses',function(Blueprint $t){$t->id();$t->string('code',50)->unique();$t->string('title');$t->string('provider')->nullable();$t->enum('delivery',['online','classroom','blended','external'])->default('online');$t->decimal('cost',12,2)->default(0);$t->unsignedInteger('duration_hours')->default(0);$t->json('skills')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('hr_learning_enrollments',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained('hr_employees')->cascadeOnDelete();$t->foreignId('course_id')->constrained('hr_learning_courses')->cascadeOnDelete();$t->enum('status',['assigned','enrolled','in_progress','completed','failed','cancelled'])->default('assigned');$t->date('due_date')->nullable();$t->timestamp('completed_at')->nullable();$t->decimal('score',5,2)->nullable();$t->string('certificate_path')->nullable();$t->timestamps();});
  Schema::create('hr_succession_plans',function(Blueprint $t){$t->id();$t->foreignId('position_id')->constrained('hr_positions')->cascadeOnDelete();$t->enum('criticality',['low','medium','high','critical'])->default('medium');$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('hr_succession_candidates',function(Blueprint $t){$t->id();$t->foreignId('succession_plan_id')->constrained('hr_succession_plans')->cascadeOnDelete();$t->foreignId('employee_id')->constrained('hr_employees')->cascadeOnDelete();$t->enum('readiness',['ready_now','ready_1_year','ready_2_years','development_needed'])->default('development_needed');$t->unsignedInteger('readiness_score')->nullable();$t->json('development_actions')->nullable();$t->timestamps();$t->unique(['succession_plan_id','employee_id']);});
 }
 public function down(): void {Schema::dropIfExists('hr_succession_candidates');Schema::dropIfExists('hr_succession_plans');Schema::dropIfExists('hr_learning_enrollments');Schema::dropIfExists('hr_learning_courses');Schema::dropIfExists('hr_employee_skills');Schema::dropIfExists('hr_skills');Schema::dropIfExists('hr_performance_reviews');Schema::dropIfExists('hr_review_cycles');Schema::dropIfExists('hr_goals');Schema::dropIfExists('hr_goal_cycles');}
};